7 table cart
Revature-Leafbound/Leafbound-API pull request #50
Opened 2022-06-13 22:09 UTC by dhruvp1320

2022-06-13 22:18 UTC, FullSol requested changes

2022-06-13 22:18 UTC, FullSol commented on src/main/java/com/leafbound/repositories/CartRepository.java
> +//    @Id
Please delete this large block of comments.

2022-06-13 22:18 UTC, FullSol commented on src/main/java/com/leafbound/repositories/CartRepository.java
> +	@Query(value="UPDATE carts SET quantity=?1 product_id=?2 id=?3 RETURNING true", nativeQuery=true)
Check out the User repository and service layers for a possible alternative to creating your own repository layer methods.

2022-06-14 21:21 UTC, L3viathon requested changes

2022-06-14 21:21 UTC, L3viathon commented on src/main/java/com/leafbound/services/CartService.java
> +	public boolean updateCart(Carts cart);
Because all we're doing with cart is either `add` or `delete` items in the cart, we don't need an `update`.

You can comment it out for now.

2022-06-14 21:21 UTC, L3viathon commented on src/main/java/com/leafbound/services/CartServiceImpl.java
> +	public boolean updateCart(Carts cart) {
Because all we're doing with cart is either `add` or `delete` items in the cart, we don't need an `update`.

You can comment it out for now.

2022-06-14 21:21 UTC, L3viathon commented on src/main/java/com/leafbound/services/CartServiceImpl.java
> +	public Products findProdById(int id) {
This method is returning `null` which is basically not implementing the method. We want to return a product.

2022-06-15 20:28 UTC, pyaeger commented
@FullSol @L3viathon - The remaining SonarCloud CODE SMELL says a block of code in Carts.java is duplicated in OrderDetails.java Lines: 26 – 43 and asks for removal of the duplication. 

The two tables are quite similar. Not sure how to resolve this. ¯\_(ツ)_/¯

2022-06-15 21:06 UTC, merged